//
//  Ruby.swift
//  TreeSitter
//
//  Created by Johannes Lund on 2016-05-04.
//  Copyright © 2016 Johannes Lund. All rights reserved.
//

import Foundation

public struct Ruby {
    public enum Symbol: UInt16, TreeSitter.Symbol {
        case sym_program = 2
        case sym__statement
        case sym__declaration
        case sym_method_declaration
        case sym_formal_parameters
        case sym_class_declaration
        case sym_module_declaration
        case sym_while_statement
        case sym_until_statement
        case sym_if_statement
        case sym_unless_statement
        case sym_for_statement
        case sym_begin_statement
        case sym_return_statement
        case sym_case_statement
        case sym_when_block
        case sym_pattern
        case sym_if_modifier
        case sym_unless_modifier
        case sym_while_modifier
        case sym_until_modifier
        case sym_condition
        case sym__statement_block
        case sym__do_block
        case sym_then_block
        case sym_else_block
        case sym_rescue_block
        case sym_ensure_block
        case sym__then_else_block
        case sym__then_elsif_else_block
        case sym__expression
        case sym__primary
        case sym_scope_resolution_expression
        case sym_subscript_expression
        case sym_member_access
        case sym_function_call
        case sym_argument_list
        case sym__argument_list
        case sym_yield
        case sym_and
        case sym_or
        case sym_not
        case sym_defined
        case sym_assignment
        case sym_conditional
        case sym_range
        case sym_boolean_or
        case sym_boolean_and
        case sym_relational
        case sym_comparison
        case sym_bitwise_or
        case sym_bitwise_and
        case sym_shift
        case sym_additive
        case sym_multiplicative
        case sym_unary_minus
        case sym_exponential
        case sym_complement
        case sym__lhs
        case sym__variable
        case sym__literal
        case sym_symbol
        case sym_boolean
        case sym_nil
        case sym_string
        case sym__quoted_string
        case sym__single_quoted_continuation
        case sym__double_quoted_continuation
        case sym__interpolated_angle
        case sym__interpolated_bracket
        case sym__interpolated_paren
        case sym__interpolated_brace
        case sym__uninterpolated_angle
        case sym__uninterpolated_bracket
        case sym__uninterpolated_paren
        case sym__uninterpolated_brace
        case sym_interpolation
        case sym_subshell
        case sym_array
        case sym__array_items
        case sym_hash
        case sym__hash_items
        case sym_pair
        case sym_regex
        case sym__regex_interpolated_angle
        case sym__regex_interpolated_bracket
        case sym__regex_interpolated_paren
        case sym__regex_interpolated_brace
        case sym_function
        case sym__function_name
        case sym__terminator
        case aux_sym_program_repeat1
        case aux_sym_formal_parameters_repeat1
        case aux_sym_class_declaration_repeat1
        case aux_sym_begin_statement_repeat1
        case aux_sym_case_statement_repeat1
        case aux_sym_rescue_block_repeat1
        case aux_sym__then_elsif_else_block_repeat1
        case aux_sym_symbol_repeat1
        case aux_sym_symbol_repeat2
        case aux_sym_symbol_repeat3
        case aux_sym_symbol_repeat4
        case aux_sym_symbol_repeat5
        case aux_sym_symbol_repeat6
        case aux_sym_symbol_repeat7
        case aux_sym_symbol_repeat8
        case aux_sym_symbol_repeat9
        case aux_sym_symbol_repeat10
        case aux_sym_symbol_repeat11
        case aux_sym_symbol_repeat12
        case aux_sym_symbol_repeat13
        case aux_sym_symbol_repeat14
        case aux_sym_symbol_repeat15
        case aux_sym_symbol_repeat16
        case aux_sym_symbol_repeat17
        case aux_sym_symbol_repeat18
        case aux_sym_symbol_repeat19
        case aux_sym_symbol_repeat20
        case aux_sym_symbol_repeat21
        case aux_sym_symbol_repeat22
        case aux_sym_symbol_repeat23
        case aux_sym_symbol_repeat24
        case aux_sym_symbol_repeat25
        case aux_sym_symbol_repeat26
        case aux_sym_symbol_repeat27
        case aux_sym_symbol_repeat28
        case aux_sym_string_repeat1
        case aux_sym_string_repeat2
        case aux_sym_string_repeat3
        case aux_sym_string_repeat4
        case aux_sym_string_repeat5
        case aux_sym_string_repeat6
        case aux_sym_string_repeat7
        case aux_sym_string_repeat8
        case aux_sym_string_repeat9
        case aux_sym_string_repeat10
        case aux_sym_string_repeat11
        case aux_sym_string_repeat12
        case aux_sym_string_repeat13
        case aux_sym_string_repeat14
        case aux_sym_string_repeat15
        case aux_sym_string_repeat16
        case aux_sym_string_repeat17
        case aux_sym_string_repeat18
        case aux_sym_string_repeat19
        case aux_sym_string_repeat20
        case aux_sym_string_repeat21
        case aux_sym_string_repeat22
        case aux_sym_string_repeat23
        case aux_sym_string_repeat24
        case aux_sym_string_repeat25
        case aux_sym_string_repeat26
        case aux_sym_string_repeat27
        case aux_sym_string_repeat28
        case aux_sym_string_repeat29
        case aux_sym__interpolated_angle_repeat1
        case aux_sym__interpolated_bracket_repeat1
        case aux_sym__interpolated_paren_repeat1
        case aux_sym__interpolated_brace_repeat1
        case aux_sym__uninterpolated_angle_repeat1
        case aux_sym__uninterpolated_bracket_repeat1
        case aux_sym__uninterpolated_paren_repeat1
        case aux_sym__uninterpolated_brace_repeat1
        case aux_sym_regex_repeat1
        case aux_sym_regex_repeat2
        case aux_sym_regex_repeat3
        case aux_sym_regex_repeat4
        case aux_sym_regex_repeat5
        case aux_sym_regex_repeat6
        case aux_sym_regex_repeat7
        case aux_sym_regex_repeat8
        case aux_sym_regex_repeat9
        case aux_sym_regex_repeat10
        case aux_sym_regex_repeat11
        case aux_sym_regex_repeat12
        case aux_sym_regex_repeat13
        case aux_sym_regex_repeat14
        case aux_sym_regex_repeat15
        case aux_sym_regex_repeat16
        case aux_sym_regex_repeat17
        case aux_sym_regex_repeat18
        case aux_sym_regex_repeat19
        case aux_sym_regex_repeat20
        case aux_sym_regex_repeat21
        case aux_sym_regex_repeat22
        case aux_sym_regex_repeat23
        case aux_sym_regex_repeat24
        case aux_sym_regex_repeat25
        case aux_sym_regex_repeat26
        case aux_sym_regex_repeat27
        case aux_sym_regex_repeat28
        case aux_sym__regex_interpolated_angle_repeat1
        case aux_sym__regex_interpolated_bracket_repeat1
        case aux_sym__regex_interpolated_paren_repeat1
        case aux_sym__regex_interpolated_brace_repeat1
        case anon_sym_LF__END__
        case sym_uninterpreted
        case anon_sym_undef
        case anon_sym_alias
        case anon_sym_def
        case anon_sym_LPAREN
        case anon_sym_RPAREN
        case anon_sym_end
        case anon_sym_STAR
        case anon_sym_AMP
        case anon_sym_COMMA
        case anon_sym_class
        case anon_sym_LT
        case anon_sym_COLON_COLON
        case anon_sym_module
        case anon_sym_while
        case anon_sym_until
        case anon_sym_if
        case anon_sym_unless
        case anon_sym_for
        case anon_sym_in
        case anon_sym_begin
        case anon_sym_return
        case anon_sym_case
        case anon_sym_when
        case anon_sym_do
        case anon_sym_then
        case anon_sym_else
        case anon_sym_rescue
        case anon_sym_ensure
        case anon_sym_elsif
        case anon_sym_LBRACK
        case anon_sym_RBRACK
        case anon_sym_DOT
        case anon_sym_yield
        case anon_sym_and
        case anon_sym_or
        case anon_sym_not
        case anon_sym_defined_QMARK
        case anon_sym_EQ
        case anon_sym_QMARK
        case anon_sym_COLON
        case anon_sym_DOT_DOT
        case anon_sym_DOT_DOT_DOT
        case anon_sym_PIPE_PIPE
        case anon_sym_AMP_AMP
        case anon_sym_EQ_EQ
        case anon_sym_BANG_EQ
        case anon_sym_EQ_EQ_EQ
        case anon_sym_LT_EQ_GT
        case anon_sym_EQ_TILDE
        case anon_sym_BANG_TILDE
        case anon_sym_LT_EQ
        case anon_sym_GT
        case anon_sym_GT_EQ
        case anon_sym_CARET
        case anon_sym_PIPE
        case anon_sym_LT_LT
        case anon_sym_GT_GT
        case anon_sym_DASH
        case anon_sym_PLUS
        case anon_sym_SLASH
        case anon_sym_PERCENT
        case anon_sym_STAR_STAR
        case anon_sym_BANG
        case anon_sym_TILDE
        case anon_sym_self
        case sym_identifier
        case sym_comment
        case aux_sym_SLASH_COLON_LPAREN_LBRACKa_DASHzA_DASHZ_RBRACK_LBRACKa_DASHzA_DASHZ0_DASH9_RBRACK_STAR_BSLASH_QMARK_QMARK_PIPE_DOT_DOT_PIPE_PIPE_PIPE_CARET_PIPE_AMP_PIPE_LT_EQ_GT_PIPE_EQ_EQ_PIPE_EQ_EQ_EQ_PIPE_EQ_TILDE_PIPE_GT_PIPE_GT_EQ_PIPE_LT_PIPE_LT_EQ_PIPE_PLUS_PIPE_DASH_PIPE_STAR_PIPE_SLASH_PIPE_PERCENT_PIPE_STAR_STAR_PIPE_LT_LT_PIPE_GT_GT_PIPE_TILDE_PIPE_PLUS_AT_PIPE_DASH_AT_PIPE_LBRACK_RBRACK_PIPE_LBRACK_RBRACK_EQ_RPAREN_SLASH
        case anon_sym_COLON_SQUOTE
        case anon_sym_COLON_DQUOTE
        case anon_sym_PERCENTs
        case aux_sym_BANG
        case aux_sym_SLASH_BSLASH_BSLASH_DOT_SLASH
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_BANG_RBRACK_SLASH
        case aux_sym_AT
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_AT_RBRACK_SLASH
        case aux_sym_POUND
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_POUND_RBRACK_SLASH
        case aux_sym_DOLLAR
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_DOLLAR_RBRACK_SLASH
        case aux_sym_PERCENT
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_PERCENT_RBRACK_SLASH
        case aux_sym_CARET
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_CARET_RBRACK_SLASH
        case aux_sym_AMP
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_AMP_RBRACK_SLASH
        case aux_sym_STAR
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_STAR_RBRACK_SLASH
        case aux_sym_RPAREN
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_RPAREN_RBRACK_SLASH
        case aux_sym_RBRACK
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_RBRACK_RBRACK_SLASH
        case aux_sym_RBRACE
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_RBRACE_RBRACK_SLASH
        case aux_sym_GT
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_GT_RBRACK_SLASH
        case aux_sym_PIPE
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_PIPE_RBRACK_SLASH
        case aux_sym_BSLASH
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_BSLASH_RBRACK_SLASH
        case aux_sym_EQ
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_EQ_RBRACK_SLASH
        case aux_sym_SLASH
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_SLASH_RBRACK_SLASH
        case aux_sym_PLUS
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_PLUS_RBRACK_SLASH
        case aux_sym_DASH
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_DASH_RBRACK_SLASH
        case aux_sym_TILDE
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_TILDE_RBRACK_SLASH
        case aux_sym_BQUOTE
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_BQUOTE_RBRACK_SLASH
        case aux_sym_SQUOTE
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_SQUOTE_RBRACK_SLASH
        case aux_sym_DQUOTE
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_DQUOTE_RBRACK_SLASH
        case aux_sym_COMMA
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_COMMA_RBRACK_SLASH
        case aux_sym_DOT
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_DOT_RBRACK_SLASH
        case aux_sym_QMARK
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_QMARK_RBRACK_SLASH
        case aux_sym_COLON
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_COLON_RBRACK_SLASH
        case aux_sym_SEMI
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_SEMI_RBRACK_SLASH
        case aux_sym__
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_RBRACK_SLASH
        case sym_integer
        case sym_float
        case anon_sym_true
        case anon_sym_false
        case anon_sym_TRUE
        case anon_sym_FALSE
        case anon_sym_nil
        case anon_sym_NIL
        case aux_sym_SLASH_PERCENTQ_QMARK_SLASH
        case aux_sym_SLASH_PERCENTq_SLASH
        case anon_sym_SQUOTE
        case anon_sym_DQUOTE
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_LT_BSLASH_GT_RBRACK_SLASH
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_LBRACK_BSLASH_RBRACK_RBRACK_SLASH
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_LPAREN_BSLASH_RPAREN_RBRACK_SLASH
        case anon_sym_LBRACE
        case aux_sym_SLASH_LBRACK_CARET_BSLASH_BSLASH_BSLASH_LBRACE_BSLASH_RBRACE_RBRACK_SLASH
        case anon_sym_RBRACE
        case aux_sym_POUND_LBRACE
        case anon_sym_PERCENTx
        case aux_sym_SLASH_PERCENT_LBRACKwi_RBRACK_SLASH
        case aux_sym_SLASH_PERCENT_LBRACKWI_RBRACK_SLASH
        case anon_sym_EQ_GT
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_SLASH_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_SLASH_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case anon_sym_PERCENTr
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_BANG_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_BANG_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_AT_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_AT_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_POUND_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_POUND_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_DOLLAR_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_DOLLAR_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_PERCENT_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_PERCENT_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_CARET_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_CARET_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_AMP_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_AMP_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_STAR_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_STAR_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_RPAREN_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_RPAREN_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_RBRACK_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_RBRACK_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_RBRACE_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_RBRACE_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_GT_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_GT_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_PIPE_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_PIPE_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_BSLASH_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_BSLASH_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_EQ_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_EQ_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_PLUS_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_PLUS_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_DASH_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_DASH_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_TILDE_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_TILDE_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_BQUOTE_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_BQUOTE_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_SQUOTE_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_SQUOTE_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_DQUOTE_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_DQUOTE_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_COMMA_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_COMMA_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_DOT_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_DOT_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_QMARK_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_QMARK_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_COLON_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_COLON_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_SEMI_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_SEMI_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_SLASH_BSLASH_LBRACK_LBRACK_CARET_BSLASH_RBRACK_BSLASHn_RBRACK_STAR_BSLASH_RBRACK_PIPE_BSLASH_BSLASH_DOT_PIPE_LBRACK_CARET_BSLASH_BSLASH_BSLASH_BSLASH_LBRACK_BSLASHn_RBRACK_SLASH
        case aux_sym_SLASH_BSLASH_LBRACKa_DASHz_RBRACK_STAR_SLASH
        case aux_sym_LT
        case aux_sym_LBRACK
        case aux_sym_LPAREN
        case aux_sym_LBRACE
        case anon_sym_DASH_GT
        case anon_sym_PLUS_AT
        case anon_sym_DASH_AT
        case anon_sym_LBRACK_RBRACK
        case anon_sym_LBRACK_RBRACK_EQ
        case sym__line_break
        case anon_sym_SEMI
        
        public var tokenType: TokenType? {
            switch self {
            case .sym_string, .sym__quoted_string, .sym__literal:
                return .String
            case .sym_integer, .sym_float:
                return .Number
            case .sym_comment, .sym_begin_statement:
                return .Comment
            case .anon_sym_do, .anon_sym_if, .anon_sym_else, .anon_sym_def, .anon_sym_nil, .anon_sym_NIL, .anon_sym_until, .anon_sym_end, .anon_sym_class, .anon_sym_module:
                return .Keyword
            case .sym_function_call, .sym__function_name, .sym_function, .sym_method_declaration:
                return TokenType.ProjectMethodNames
            default:
                return nil
            }
        }
        
        public var isOpaque: Bool {
            return true
        }
    }
}